name: DigitalOcean App workflow

on:
  push:
    branches: [ main ]

env:
  REGISTRY: "registry.digitalocean.com/spring-boot-demo-registry"
  IMAGE_NAME: "demo"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven Package
        run: chmod +x mvnw && ./mvnw clean package -DskipTests
      - name: Login to DockerHub
        if: GitHub.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/latest
      - name: Connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            docker pull amtamusic/Sorting-Algorithm-API-Visualizer:latest
            docker rm -f terminal-commands
            docker run -d --name terminal-commands -p 8090:8090 hsmnzaydn/terminal-commands
      - name: Deploy