name: DigitalOcean App workflow

on:
  push:
    branches: [ main ]

env:
  REGISTRY: "registry.digitalocean.com/spring-boot-demo-registry"
  IMAGE_NAME: "demo"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven Package
        run: chmod +x mvnw && ./mvnw clean package -DskipTests
      - name: Login to DockerHub
        if: GitHub.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sorting-algorithms:latest
      - name: Connect
        uses: appleboy/ssh-action@master
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_HUB_USERNAME,DOCKER_HUB_PASSWORD
          debug: true
          script: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker pull doomslayer92/sorting-algorithms:latest
            docker rm -f sorting-algorithms
            docker run -d --restart always --name sorting-algorithms -p 8080:8080 doomslayer92/sorting-algorithms:latest